ProductsServiceURL: http://Microservices.Monitoring.Products.API/api/products
ElasticApm:
    SecretToken: 
    ServerUrls: http://apm-server:8200
    ServiceName: Microservices.Monitoring.Client.MVC
    Environment: production
